  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Publications"
  weight = 200
  identifier = "publications"
  url = "/publications/"


  [[main]]
  name = "CV"
  weight = 400
  url = "/CV_Janis_Fiedler_eng"

  #[[main]]
  #name = "Accomplishments"
  #weight = 500
  #identifier = "accomplishments"

  #[[main]]
 # name = "Awards"
  #weight = 510
  #identifier = "awards"
  #url = "/awards/"
  #parent = "accomplishments"  


  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"